name: my-first

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: バージョンは？

env:
  WORKING_DIRECTORY: application

jobs:
  show_input_value:
    name: Show Input Value
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Show
        run: |
          echo ${{ github.event.inputs.version }}
          echo "GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}"

  read_environment_value:
    name: Read Variables File Value
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Set Environment Variables
        uses: ./.github/actions
        with:
            varFilePath: ./.github/variables/variables.env

      - name: Read Environment Variables
        run: |
          echo $env.APP_VERSION
          echo ${{ env.MAGIC_NUMBER }}