name: my-first

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: バージョンは？

jobs:
  show_input_value:
    name: Show Input Value
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Show
        run: |
          echo ${{ github.event.inputs.version }}
          echo "GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}"

      - name: read another file env
        run: |
          echo ${{ env.APP_VERSION }}
          echo ${{ env.MAGIC_NUMBER }}

  read_second_value:
    name: Read Second YAML Value
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: ./github/workflows/second.yml

      - name: Read Variables
        run: |
          echo ${{ env.APP_VERSION }}