name: second

on:
  workflow_dispatch:


env:
  APP_VERSION: "2024.3.1"
  MAGIC_NUMBER: "1"

jobs:
  shon_env_value:
    name: Show Env Value
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Show
        run: |
            echo ${APP_VERSION}
            echo ${MAGIC_NUMBER}