name: second

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: false
        description: バージョンは？
        default: "${APP_VERSION}"

      selected:
        type: boolean
        required: false
        description: リリースアーカイブ作成/バージョンアップ？
        default: true

env:
  APP_VERSION: "2024.3.1"
  MAGIC_NUMBER: "1"

jobs:
  shon_env_value:
    name: Show Env Value
    if: ${{ inputs.selected }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Show
        run: |
            echo "APP_VERSION=${APP_VERSION}"
            echo "MAGIC_NUMBER=${MAGIC_NUMBER}"
            echo "input version=${{ github.event.inputs.version }}"
            echo "run branch=" $(git branch --show-current | sed 's|/|-|g')

      - name: update env
        run: |
          echo "APP_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          echo "MAGIC_NUMBER=$(($MAGIC_NUMBER + $GITHUB_RUN_NUMBER))" >> $GITHUB_ENV

      - name: after update env
        run: |
          echo ${APP_VERSION}
          echo ${MAGIC_NUMBER}