name: version-up

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: バージョンは？

jobs:
  create_tag:
    name: Create_Tag
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - run: git fetch origin $(git branch --show-current)
      - run: git checkout $(git branch --show-current)
      - run: git tag tag-v${{ github.event.inputs.version }}
      - run: git push origin tag-v${{ github.event.inputs.version }}


      - name: get APP_VERSION
        run: |
          echo ${{ vars.ENV_CONTEXT_VAR }}