name: version-up

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: バージョンは？

jobs:
  create_tag:
    name: Create Tag
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Create Tag
        run: |
          git fetch origin $(git branch --show-current)
          git checkout $(git branch --show-current)
          git tag tag-v${{ github.event.inputs.version }}
          git push origin tag-v${{ github.event.inputs.version }}

  update_version:
    name: Update Version
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Get Variables
        run: |
          echo ${{ vars.APP_VERSION }}
          echo ${{ vars.MAGIC_NUMBER }}

      - name: Update Variables
        run: |
          curl -L \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/fujipon1126/study-app/actions/variables/APP_VERSION \
          -d '{"name":"APP_VERSION","value":${{ github.event.inputs.version }}}'

      - name: After Variables
        run: |
          echo ${{ vars.APP_VERSION }}
          echo ${{ vars.MAGIC_NUMBER }}